### ISSUE TITLE
Bug with Program

### ISSUE THREAD

**Issue by tutugoy** [therealtutugoy/C-Launguage_Projects#1]
**THIS IS A TEST/EXAMPLE ON HOW TO REPORT ISSUES**
Hey! There is a issue with a program. It's name is Dozens Converter and I hope it gets fixed! Thanks

**Comment by therealtutugoy** [comment]
yes like i said this is still a test:-
Ok, I will fix it soon!

**Comment by therealtutugoy** [comment]
still test:-
Hey, thanks for waiting. it is fixed now. Feel free to use
